name: test
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - run: npm ci
      - run: npm run dist
      - run: npm run lint-js
      - run: npm run lint-md
      - run: npm test
